/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Coins { 'irn' : number, 'usdt' : number }
export type ExternalBlob = Uint8Array;
export interface Game {
  'id' : bigint,
  'thumbnail' : ExternalBlob,
  'name' : string,
  'description' : string,
  'gameUrl' : string,
  'category' : SportCategory,
}
export interface PlayerScore {
  'username' : string,
  'score' : bigint,
  'category' : SportCategory,
}
export type SportCategory = { 'Basketball' : null } |
  { 'Tennis' : null } |
  { 'Shooting' : null } |
  { 'Football' : null } |
  { 'Cricket' : null } |
  { 'Badminton' : null } |
  { 'Racing' : null };
export interface UserProfile {
  'username' : string,
  'balance' : Coins,
  'userId' : bigint,
  'name' : string,
  'role' : { 'admin' : null } |
    { 'user' : null },
  'email' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface WithdrawRequest {
  'status' : { 'pending' : null } |
    { 'approved' : null },
  'requestId' : bigint,
  'userId' : bigint,
  'upiId' : string,
  'amount' : string,
}
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addGame' : ActorMethod<
    [string, SportCategory, ExternalBlob, string, string],
    undefined
  >,
  'addPlayerScore' : ActorMethod<[string, bigint, SportCategory], undefined>,
  'approveWithdrawRequest' : ActorMethod<[bigint], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteWithdrawRequest' : ActorMethod<[bigint], undefined>,
  'getAllGames' : ActorMethod<[], Array<Game>>,
  'getAllUsers' : ActorMethod<[], Array<UserProfile>>,
  'getAllWithdrawRequests' : ActorMethod<[], Array<WithdrawRequest>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getGameById' : ActorMethod<[bigint], Game>,
  'getMyProfile' : ActorMethod<[bigint], UserProfile>,
  'getTopScores' : ActorMethod<[], Array<PlayerScore>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isAdminCaller' : ActorMethod<[], boolean>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'registerUser' : ActorMethod<[string, string, string], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'submitWithdrawRequest' : ActorMethod<[bigint, string, string], bigint>,
  'updateProfile' : ActorMethod<[bigint, string, string, string], undefined>,
  'updateUserProfile' : ActorMethod<
    [bigint, string, string, string],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];