/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const SportCategory = IDL.Variant({
  'Basketball' : IDL.Null,
  'Tennis' : IDL.Null,
  'Shooting' : IDL.Null,
  'Football' : IDL.Null,
  'Cricket' : IDL.Null,
  'Badminton' : IDL.Null,
  'Racing' : IDL.Null,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Game = IDL.Record({
  'id' : IDL.Nat,
  'thumbnail' : ExternalBlob,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'gameUrl' : IDL.Text,
  'category' : SportCategory,
});
export const Coins = IDL.Record({ 'irn' : IDL.Float64, 'usdt' : IDL.Float64 });
export const UserProfile = IDL.Record({
  'username' : IDL.Text,
  'balance' : Coins,
  'userId' : IDL.Nat,
  'name' : IDL.Text,
  'role' : IDL.Variant({ 'admin' : IDL.Null, 'user' : IDL.Null }),
  'email' : IDL.Text,
});
export const WithdrawRequest = IDL.Record({
  'status' : IDL.Variant({ 'pending' : IDL.Null, 'approved' : IDL.Null }),
  'requestId' : IDL.Nat,
  'userId' : IDL.Nat,
  'upiId' : IDL.Text,
  'amount' : IDL.Text,
});
export const PlayerScore = IDL.Record({
  'username' : IDL.Text,
  'score' : IDL.Nat,
  'category' : SportCategory,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addGame' : IDL.Func(
      [IDL.Text, SportCategory, ExternalBlob, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'addPlayerScore' : IDL.Func([IDL.Text, IDL.Nat, SportCategory], [], []),
  'approveWithdrawRequest' : IDL.Func([IDL.Nat], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteWithdrawRequest' : IDL.Func([IDL.Nat], [], []),
  'getAllGames' : IDL.Func([], [IDL.Vec(Game)], ['query']),
  'getAllUsers' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
  'getAllWithdrawRequests' : IDL.Func(
      [],
      [IDL.Vec(WithdrawRequest)],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getGameById' : IDL.Func([IDL.Nat], [Game], ['query']),
  'getMyProfile' : IDL.Func([IDL.Nat], [UserProfile], ['query']),
  'getTopScores' : IDL.Func([], [IDL.Vec(PlayerScore)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isAdminCaller' : IDL.Func([], [IDL.Bool], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'registerUser' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'submitWithdrawRequest' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'updateProfile' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text, IDL.Text], [], []),
  'updateUserProfile' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const SportCategory = IDL.Variant({
    'Basketball' : IDL.Null,
    'Tennis' : IDL.Null,
    'Shooting' : IDL.Null,
    'Football' : IDL.Null,
    'Cricket' : IDL.Null,
    'Badminton' : IDL.Null,
    'Racing' : IDL.Null,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Game = IDL.Record({
    'id' : IDL.Nat,
    'thumbnail' : ExternalBlob,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'gameUrl' : IDL.Text,
    'category' : SportCategory,
  });
  const Coins = IDL.Record({ 'irn' : IDL.Float64, 'usdt' : IDL.Float64 });
  const UserProfile = IDL.Record({
    'username' : IDL.Text,
    'balance' : Coins,
    'userId' : IDL.Nat,
    'name' : IDL.Text,
    'role' : IDL.Variant({ 'admin' : IDL.Null, 'user' : IDL.Null }),
    'email' : IDL.Text,
  });
  const WithdrawRequest = IDL.Record({
    'status' : IDL.Variant({ 'pending' : IDL.Null, 'approved' : IDL.Null }),
    'requestId' : IDL.Nat,
    'userId' : IDL.Nat,
    'upiId' : IDL.Text,
    'amount' : IDL.Text,
  });
  const PlayerScore = IDL.Record({
    'username' : IDL.Text,
    'score' : IDL.Nat,
    'category' : SportCategory,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addGame' : IDL.Func(
        [IDL.Text, SportCategory, ExternalBlob, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'addPlayerScore' : IDL.Func([IDL.Text, IDL.Nat, SportCategory], [], []),
    'approveWithdrawRequest' : IDL.Func([IDL.Nat], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteWithdrawRequest' : IDL.Func([IDL.Nat], [], []),
    'getAllGames' : IDL.Func([], [IDL.Vec(Game)], ['query']),
    'getAllUsers' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
    'getAllWithdrawRequests' : IDL.Func(
        [],
        [IDL.Vec(WithdrawRequest)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getGameById' : IDL.Func([IDL.Nat], [Game], ['query']),
    'getMyProfile' : IDL.Func([IDL.Nat], [UserProfile], ['query']),
    'getTopScores' : IDL.Func([], [IDL.Vec(PlayerScore)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isAdminCaller' : IDL.Func([], [IDL.Bool], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'registerUser' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'submitWithdrawRequest' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'updateProfile' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text, IDL.Text], [], []),
    'updateUserProfile' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };